CREATE TABLE tags (id BIGINT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE proposal_tags (proposal_id BIGINT NOT NULL,tag_id BIGINT NOT NULL,PRIMARY KEY(proposal_id,tag_id),CONSTRAINT fk_pt_proposal FOREIGN KEY(proposal_id) REFERENCES proposals(id) ON DELETE CASCADE,CONSTRAINT fk_pt_tag FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE CASCADE);
